/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ajozqvw2mneihocsdaevohbquy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-c57zeyt2h5dx5hdna7s77yogia",
    "aws_cognito_identity_pool_id": "us-east-1:0a7646d8-2973-4a18-a709-0e3be9f98e00",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1S8VTlOec",
    "aws_user_pools_web_client_id": "4l8vtv9nrijvakh0sskg11grdb",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "scribestorage221711-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
