/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://szmrhvfd3fgszoszqmxfg2r7lm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mn36uray7bf6zf3p2pnxp32r3q",
    "aws_cognito_identity_pool_id": "us-east-1:4ed3abe8-8fa3-441d-b04a-a2fc1e555a70",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NSR22wSow",
    "aws_user_pools_web_client_id": "ojs3fa9jsv4hdgod5s4kpgq0g",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "scribe-storage165716-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
